// Generated by CoffeeScript 1.8.0
var DocxType, fs, mammoth, path, _wrap;

fs = require("fs-extra");

path = require("path");

mammoth = require("mammoth");

DocxType = (function() {
  function DocxType(srcfile, destfile) {
    this.srcfile = srcfile;
    this.destfile = destfile;
    this.options = {};
    this.srcfile = path.normalize(srcfile);
    if (destfile) {
      this.destfile = path.normalize(destfile);
    } else {
      this.destfile = srcfile + ".html";
    }
  }

  DocxType.prototype.tune = function() {};

  DocxType.prototype["do"] = function(cb) {
    return mammoth.convertToHtml({
      path: this.srcfile
    }, this.options).then((function(_this) {
      return function(r) {
        var result;
        result = _wrap(r.value);
        return fs.writeFile(_this.destfile, result, cb);
      };
    })(this)).done();
  };

  return DocxType;

})();

_wrap = function(v) {
  return '<html><head><meta charset="utf-8"></head><body>' + v + '</body><html>';
};

module.exports = DocxType;
