// Generated by CoffeeScript 1.8.0
module.exports = {
  pdf: {
    "default": ['--zoom', '1.33'],
    ipad: ['--fit-width', '968']
  },
  docx: {},
  unoconv: {},
  saveNamedOptions: function(type, name, opts) {
    if (!type || (module.exports[type] == null)) {
      return "Указаный тип источника не предусмотрен (pdf,docx,unoconv)";
    }
    if (!name) {
      return "Не указано имя";
    }
    if (opts) {
      if (!Array.isArray(opts)) {
        return "Опции должны быть массивом строк";
      }
      return module.exports[type][name] = opts;
    } else {
      return delete module.exports[type][name];
    }
  }
};
