// Generated by CoffeeScript 1.8.0
var busy, stack;

stack = [];

busy = null;

module.exports = {
  setNext: function(obj, cb) {
    stack.unshift({
      "class": obj,
      cbk: cb
    });
    return setTimeout(module.exports.makeNext, 50);
  },
  makeNext: function() {
    var next;
    if (busy || stack.length === 0) {
      return;
    }
    busy = true;
    next = stack.pop();
    return next["class"].make(function(err) {
      busy = null;
      next.cbk(err);
      module.exports.makeNext();
    });
  }
};
